apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: ns-mysqlphp
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
