apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: ns-mysqlphp
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
