apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db
  namespace: ns-mysqlphp
data:
  create_table.sql: |
    CREATE TABLE example_table (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
