apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp 
    spec:
      containers:
      - name: webapp
        image: 192.168.49.2:5000/webapp:2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80